### ISSUE TITLE
혹시 멀티 쓰레딩으로 돌리면 XX 같은 문자열 생기나요??

### ISSUE THREAD

**Issue by kdrkdrkdr** [stypr/ehnd-py#1]
XX 같은 문자열도 생기고, 제대로 배열되지 않은 "궯" 같은 문자열도 생깁니다..
다른 언어에서는 안  그렇다는데 파이썬에서만 그러는지는 잘 모르겠네요..

threading.Thread() 로 돌렸습니다.

**Comment by stypr** [comment]
쓰레딩으론 테스트하진 않았는데.. 아마 쓰레드로 돌리면 안될 수도 있을 것 같긴 합니다.. 따로 비동기처리를 하면 해결될지도 모르겠네요.. 어짜피 코드 조금 수정하면 쓰레드가 꼬여도 해결은 가능해보여서요..
시간날때 확인해보고 문제가 있으면 수정해볼게요. 아마 인코딩 문제일 수도 있어요.

**Comment by kdrkdrkdr** [comment]
비동기로 짜니까 해결됬습니다.
감사합니다^^
